"""Run Command System Utility Functions

Provides helper functions for theme slug generation, path handling, etc.
"""

import re
import time
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from slugify import slugify as _slugify

# Legacy run dir naming pattern: yyyyMMdd-{slug}
_LEGACY_RUN_PREFIX_RE = re.compile(r"^\d{8}-")
# Cross-domain prefix (case-insensitive)
_CROSS_PREFIX_RE = re.compile(r"^CROSS-", re.IGNORECASE)


def generate_theme_slug(description: str, max_length: int = 90) -> str:
    """Generate theme slug (date prefix + slugified description)

    Args:
        description: original task description (should be a concise theme phrase generated by AI)
        max_length: maximum length limit (excluding date prefix)

    Returns:
        date prefix + slugified theme name (format: yyyyMMdd-slug)

    Examples:
        >>> generate_theme_slug("nano-banana-pro image api research")
        '20251203-nano-banana-pro-image-api-research'
        >>> generate_theme_slug("upwork python jobs search")
        '20251203-upwork-python-jobs-search'

    Note:
        AI should provide English theme phrases directly (3-5 words) to avoid unreadability from Chinese pinyin conversion
    """
    # Date prefix (yyyyMMdd)
    date_prefix = datetime.now().strftime("%Y%m%d")

    # Slugify directly (keep English, numbers, remove Chinese and special characters)
    slug = _slugify(description, max_length=max_length)

    # If empty (pure symbols or pure Chinese input), fallback to timestamp
    if not slug:
        slug = f"task-{int(time.time())}"

    return f"{date_prefix}-{slug}"


def is_valid_run_id(run_id: str) -> bool:
    """Validate run_id format.

    Phase 1: now also allows uppercase to support ``CROSS-`` prefix.

    Args:
        run_id: run ID to validate

    Returns:
        True if valid, False otherwise
    """
    # Allow uppercase (CROSS- prefix), lowercase, digits, hyphens; max 100 chars
    pattern = r"^[A-Za-z0-9-]{1,100}$"
    return bool(re.match(pattern, run_id))


def parse_cross_domain(name: str) -> Optional[List[str]]:
    """Parse a cross-domain run name into its component domains.

    A cross-domain run is named ``CROSS-<domain1>-<domain2>[-...]``.

    Args:
        name: directory / domain name

    Returns:
        List of component domain names if ``name`` has the ``CROSS-`` prefix,
        otherwise ``None``.

    Examples:
        >>> parse_cross_domain("CROSS-twitter-feishu")
        ['twitter', 'feishu']
        >>> parse_cross_domain("twitter") is None
        True
    """
    if not _CROSS_PREFIX_RE.match(name):
        return None
    remainder = name[len("CROSS-"):]
    if not remainder:
        return []
    return [part for part in remainder.split("-") if part]


def is_legacy_run_dir(name: str) -> bool:
    """Detect legacy ``YYYYMMDD-<slug>`` style run directory names.

    Args:
        name: directory name (not full path)

    Returns:
        True when ``name`` starts with 8 digits followed by a hyphen.
    """
    return bool(_LEGACY_RUN_PREFIX_RE.match(name))


def normalize_domain_name(raw: str) -> str:
    """Normalize a raw domain name into the canonical on-disk form.

    Rules:
    - If ``raw`` starts with a (case-insensitive) ``CROSS-`` prefix, the prefix
      is preserved as ``CROSS-`` and the remainder is slugified (lowercase).
    - Otherwise, the whole string is slugified (lowercase, kebab-case).

    Args:
        raw: user-provided domain name or theme description

    Returns:
        Normalized domain name suitable for use as a directory name.
    """
    if not raw:
        return ""
    cross_match = _CROSS_PREFIX_RE.match(raw)
    if cross_match:
        remainder = raw[cross_match.end():]
        slugged = _slugify(remainder, max_length=90)
        if not slugged:
            return "CROSS-"
        return f"CROSS-{slugged}"
    slugged = _slugify(raw, max_length=90)
    if not slugged:
        slugged = f"task-{int(time.time())}"
    return slugged


def scan_run_directories(projects_dir: Path) -> List[str]:
    """Scan projects directory and return all run_id list

    Args:
        projects_dir: projects directory path

    Returns:
        list of run_ids (sorted by last modified time in descending order)
    """
    if not projects_dir.exists() or not projects_dir.is_dir():
        return []

    run_ids = []
    for item in projects_dir.iterdir():
        if item.is_dir() and is_valid_run_id(item.name):
            run_ids.append(item.name)

    # Sort by last modified time (most recent first)
    run_ids.sort(key=lambda rid: (projects_dir / rid).stat().st_mtime, reverse=True)

    return run_ids


def ensure_directory_exists(path: Path) -> None:
    """Ensure directory exists (create if it doesn't exist)

    Args:
        path: directory path

    Raises:
        FileSystemError: directory creation failed
    """
    from .exceptions import FileSystemError

    try:
        path.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        raise FileSystemError("create directory", str(path), str(e))
